image: Ubuntu2004

stack: jdk 11

branches:
  only:
    - main  # ветка git

build: off

install:

  - java -jar ./artifacts/app-order.jar &
  - chmod +x gradlew

build_script:
  - ./gradlew test --info